FROM node:18.20.6-slim

RUN apt-get update && \
    apt-get install -y openssl less locales git vim && \
    apt-get clean

RUN echo "ja_JP UTF-8" > /etc/locale.gen && locale-gen
ENV LANG=ja_JP.UTF-8

WORKDIR /workspace/web

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN ["npm", "install"]

COPY schema.prisma ./
RUN npx prisma generate --schema schema.prisma --generator client

CMD ["npm", "run", "dev:docker"]
